import sun.jvm.hotspot.debugger.win32.coff.TestParser;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class TailwindUtility {
    public List<String> classOrder = Collections.emptyList();

    public TailwindUtility() {
        try {
            // Read this classOrder generated by the reading the classes, in order, from the TailwindCss file
            classOrder = Files.readAllLines(Paths.get(TailwindUtility.class.getResource("classes.txt").toURI()));
        } catch (Exception e) {
            // I should probably do something here on the off chance we're missing that file
        }
    }
}
